// hexadash-svelte/hexadash/src/lib/view/dashboard/demoTen/Inbox.svelte
<script>
	import { Card, CardHeader, CardBody } from '@sveltestrap/sveltestrap';
	import CardExtra from '@components/cards/CardExtra.svelte';

	const inboxData = [
		{
			id: 1,
			user: {
				fName: 'Shane',
				lName: 'Watson',
				msg: 'We are looking a full stack developer',
				img: '/img/inbox-1.png'
			},
			time: '9:00 AM'
		},
		{
			id: 2,
			user: {
				fName: 'Chris',
				lName: 'Dohan',
				msg: 'Well done, great work ',
				img: '/img/inbox-2.png'
			},
			time: '9:30 AM'
		},
		{
			id: 3,
			user: {
				fName: 'Robert',
				lName: 'Clinton',
				msg: 'Tonight we are going to submit new...',
				img: '/img/inbox-3.png'
			},
			time: '9:30 AM'
		},
		{
			id: 4,
			user: {
				fName: 'Daniel',
				lName: 'White',
				msg: 'Please send me final file',
				img: '/img/inbox-1.png'
			},
			time: '9:30 AM'
		},
		{
			id: 5,
			user: {
				fName: 'Black',
				lName: 'Smith',
				msg: 'Good luck Tom',
				img: '/img/inbox-2.png'
			},
			time: '9:30 AM'
		}
	];
</script>

<Card class="border-0 card-inbox">
	<CardHeader class="border-0">
		<h6>Inbox</h6>
		<CardExtra />
	</CardHeader>
	<CardBody class="pb-40 pt-0">
		<div class="card-inbox-members">
			<ul>
				{#each inboxData as item}
					<li>
						<div class="card-inbox-members__left">
							<img class="rounded-circle" src={item.user.img} alt="" />
							<div class="card-inbox-members__title">
								<h6>{item.user.fName} {item.user.lName}</h6>
								<div class="card-inbox-members__title--online">
									{item.user.msg}
								</div>
							</div>
						</div>
						<div class="card-inbox-member__right">
							<div class="card-inbox-member__time">
								<span>{item.time}</span>
							</div>
						</div>
					</li>
				{/each}
			</ul>
		</div>
	</CardBody>
</Card>

<style lang="scss">
	/* inbox */
	@import '../../../../assets/sass/mixins/media-queries';
	.card-inbox {
		.card-inbox-members {
			ul {
				li {
					display: flex;
					align-items: center;
					justify-content: space-between;

					&:not(:last-child) {
						margin-bottom: 15px;
					}

					.card-inbox-members__left {
						display: flex;
						align-items: center;

						img {
							margin-right: 12px;
							width: 34px;
							height: 34px;
						}

						.card-inbox-members__title {
							h6 {
								font-size: 15px;
								font-weight: 500;
								color: var(--color-gray);
							}

							.card-inbox-members__title--online {
								font-size: 14px;
								font-weight: 400;
								color: var(--color-light);
								margin-top: 2px;
							}
						}
					}

					.card-inbox-member__time {
						span {
							font-size: 14px;
							font-weight: 400;
							color: var(--color-light);
							@include ssm {
								font-size: 12px;
							}
						}
					}
				}
			}
		}
	}
</style>

// hexadash-react/documentation/src/container/dashboard/overview/demoFive/Inbox.js
import React from 'react';
import UilPrint from '@iconscout/react-unicons/icons/uil-print';
import UilBookOpen from '@iconscout/react-unicons/icons/uil-book-open';
import UilFileAlt from '@iconscout/react-unicons/icons/uil-file-alt';
import UilFile from '@iconscout/react-unicons/icons/uil-file';
import UilTimes from '@iconscout/react-unicons/icons/uil-times';
import { Link } from 'react-router-dom';
import { List, Avatar } from 'antd';
import { Cards } from '../../../../components/cards/frame/cards-frame';
import { BorderLessHeading } from '../../../styled';
import { InboxListStyleWrap } from '../../Style';

const inboxData = [
  {
    id: 1,
    user: {
      fName: 'Shane',
      lName: 'Watson',
      msg: 'We are looking a full stack developer',
    },
    time: '9:00 AM',
    theme: '#00AAFF',
  },
  {
    id: 2,
    user: {
      fName: 'Chris',
      lName: 'Dohan',
      msg: 'Well done, great work ',
      img: 'static/img/sellers/11.png',
    },
    time: '9:30 AM',
    theme: '#00AAFF',
  },
  {
    id: 3,
    user: {
      fName: 'Robert',
      lName: 'Clinton',
      msg: 'Tonight we are going to submit new...',
    },
    time: '9:30 AM',
    theme: '#FB3586',
  },
  {
    id: 4,
    user: {
      fName: 'Daniel',
      lName: 'White',
      msg: 'Please send me final file',
      img: 'static/img/sellers/12.png',
    },
    time: '9:30 AM',
    theme: '#FB3586',
  },
  {
    id: 5,
    user: {
      fName: 'Black',
      lName: 'Smith',
      msg: 'Good luck Tom',
    },
    time: '9:30 AM',
    theme: '#5840FF',
  },
];

const Inbox = () => {
  const moreContent = (
    <>
      <Link to="#">
        <UilPrint />
        <span>Printer</span>
      </Link>
      <Link to="#">
        <UilBookOpen />
        <span>PDF</span>
      </Link>
      <Link to="#">
        <UilFileAlt />
        <span>Google Sheets</span>
      </Link>
      <Link to="#">
        <UilTimes />
        <span>Excel (XLSX)</span>
      </Link>
      <Link to="#">
        <UilFile />
        <span>CSV</span>
      </Link>
    </>
  );
  return (
    <BorderLessHeading>
      <InboxListStyleWrap>
        <Cards title="Inbox" more={moreContent}>
          <List
            className="demo-loadmore-list"
            itemLayout="horizontal"
            dataSource={inboxData}
            renderItem={item => (
              <List.Item>
                <List.Item.Meta
                  avatar={
                    item.user.img ? (
                      <Avatar shape="square" src={require(`../../../../${item.user.img}`)} />
                    ) : (
                      <Avatar shape="square" style={{ backgroundColor: item.theme }}>
                        {item.user.fName[0]}
                        {item.user.lName[0]}
                      </Avatar>
                    )
                  }
                  title={
                    <Link to="#">
                      {item.user.fName} {item.user.lName}
                    </Link>
                  }
                  description={item.user.msg}
                />
                <span className="ninjadash-mail-time">{item.time}</span>
              </List.Item>
            )}
          />
        </Cards>
      </InboxListStyleWrap>
    </BorderLessHeading>
  );
};

export default Inbox;
