// hexadash-react/documentation/src/container/forms/overview/HorizontalForm.js
import React, { useEffect } from 'react';
import { Row, Col, Form, Input, Button } from 'antd';
import { HorizontalFormStyleWrap } from './Style';
import Prism from "prismjs";
import { Cards } from '../../../components/cards/frame/cards-frame';
import { BasicFormWrapper } from '../../styled';

const HorizontalForm = () => {
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <BasicFormWrapper>
      <HorizontalFormStyleWrap>
        <Cards title="Horizontal Form">
          <Form name="horizontal-form" layout="horizontal">
            <Row align="middle">
              <Col lg={8} md={9} xs={24}>
                <label htmlFor="name">Name</label>
              </Col>
              <Col lg={16} md={15} xs={24}>
                <Form.Item name="name" initialValue="Duran Clayton">
                  <Input placeholder="Enter Name" />
                </Form.Item>
              </Col>
            </Row>
            <Row align="middle">
              <Col lg={8} md={9} xs={24}>
                <label htmlFor="email">Email Address</label>
              </Col>
              <Col lg={16} md={15} xs={24}>
                <Form.Item name="email" initialValue="username@email.com">
                  <Input placeholder="Enter Email" />
                </Form.Item>
              </Col>
            </Row>
            <Row align="middle">
              <Col lg={8} md={9} xs={24}>
                <label htmlFor="password">Password</label>
              </Col>
              <Col lg={16} md={15} xs={24}>
                <Form.Item name="password" initialValue="1234567">
                  <Input.Password placeholder="Enter Password" />
                </Form.Item>
              </Col>
            </Row>
            <Row>
              <Col lg={{ span: 16, offset: 8 }} md={{ span: 15, offset: 9 }} xs={{ span: 24, offset: 0 }}>
                <div className="ninjadash-form-action">
                  <Button className="btn-signin" htmlType="submit" type="light" size="large">
                    Cancel
                  </Button>
                  <Button className="btn-signin" type="primary" size="large">
                    Save
                  </Button>
                </div>
              </Col>
            </Row>
          </Form>
          <div className="docs-highlighter mt-35">
                        <pre>
                            <code className="language-javascript">
{
`
import { Form, Input, Button } from 'antd';
import { HorizontalFormStyleWrap } from './Style';
import { BasicFormWrapper } from '../../styled';

const HorizontalForm = () => {
  return (
    <Form name="horizontal-form" layout="horizontal">
      <Row align="middle">
        <Col lg={8} md={9} xs={24}>
          <label htmlFor="name">Name</label>
        </Col>
        <Col lg={16} md={15} xs={24}>
          <Form.Item name="name" initialValue="Duran Clayton">
            <Input placeholder="Enter Name" />
          </Form.Item>
        </Col>
      </Row>
      <Row align="middle">
        <Col lg={8} md={9} xs={24}>
          <label htmlFor="email">Email Address</label>
        </Col>
        <Col lg={16} md={15} xs={24}>
          <Form.Item name="email" initialValue="username@email.com">
            <Input placeholder="Enter Email" />
          </Form.Item>
        </Col>
      </Row>
      <Row align="middle">
        <Col lg={8} md={9} xs={24}>
          <label htmlFor="password">Password</label>
        </Col>
        <Col lg={16} md={15} xs={24}>
          <Form.Item name="password" initialValue="1234567">
            <Input.Password placeholder="Enter Password" />
          </Form.Item>
        </Col>
      </Row>
      <Row>
        <Col 
        lg={{ span: 16, offset: 8 }} 
        md={{ span: 15, offset: 9 }} 
        xs={{ span: 24, offset: 0 }}
        >
          <div className="ninjadash-form-action">
            <Button className="btn-signin" htmlType="submit" type="light" size="large">
              Cancel
            </Button>
            <Button className="btn-signin" type="primary" size="large">
              Save
            </Button>
          </div>
        </Col>
      </Row>
    </Form>
  );
};
export { HorizontalForm };
`
}
                            </code>
                        </pre>
                    </div>
        </Cards>
      </HorizontalFormStyleWrap>
    </BasicFormWrapper>
  );
};

export { HorizontalForm };

// hexadash-vue/full-version/src/view/forms/overview/HorizontalForm.vue
<template>
  <HorizontalFormStyleWrap>
    <sdCards title="Horizontal Form">
      <a-form
        :layout="formState.layout"
        :model="formState"
        :label-col="labelCol"
        :wrapper-col="wrapperCol"
        labelAlign="left"
      >
        <a-form-item label="Name">
          <a-input
            v-model:value="formState.name"
            placeholder="input placeholder"
          />
        </a-form-item>
        <a-form-item label="Email Address">
          <a-input
            v-model:value="formState.emailAddress"
            placeholder="input placeholder"
          />
        </a-form-item>
        <a-form-item label="Password">
          <a-input-password
            v-model:value="formState.password"
            placeholder="input placeholder"
          />
        </a-form-item>
        <a-row>
          <a-col
            :lg="{ span: 16, offset: 8 }"
            :md="{ span: 15, offset: 9 }"
            :xs="{ span: 24, offset: 0 }"
          >
            <div class="ninjadash_form-action">
              <sdButton
                class="ninjadash_form-action__btn"
                size="lg"
                html-type="submit"
                type="light"
              >
                Cancel
              </sdButton>
              <sdButton
                class="ninjadash_form-action__btn"
                type="primary"
                size="lg"
              >
                Save
              </sdButton>
            </div>
          </a-col>
        </a-row>
      </a-form>
    </sdCards>
  </HorizontalFormStyleWrap>
</template>

<script>
import { reactive, defineComponent } from "vue";
import { HorizontalFormStyleWrap } from "./Style";
export default defineComponent({
  name: "HorizantalForm",
  components: {
    HorizontalFormStyleWrap,
  },
  setup() {
    const formState = reactive({
      layout: "horizontal",
      name: "Duran Clayton",
      emailAddress: "username@email.com",
      password: "123456",
    });

    const labelCol = {
      lg: 8,
      md: 9,
      xs: 24,
    };
    const wrapperCol = {
      lg: 16,
      md: 15,
      xs: 24,
    };

    return {
      formState,
      labelCol,
      wrapperCol,
    };
  },
});
</script>
