// hexadash-react-tailwind/documentation/src/components/maps/leaflet.js
import React from 'react';
import { MapContainer, Marker, Popup, TileLayer } from 'react-leaflet';
import PropTypes from 'prop-types';
import 'leaflet/dist/leaflet.css';
// eslint-disable-next-line import/no-unresolved
import 'leaflet/dist/leaflet.css?url=false';
import 'leaflet.markercluster/dist/MarkerCluster.css';
import 'leaflet.markercluster/dist/MarkerCluster.Default.css';
import 'react-leaflet-markercluster/dist/styles.min.css';
import MarkerClusterGroup from 'react-leaflet-markercluster';
import L from 'leaflet';
import { GmapWraper } from './map-style';

// eslint-disable-next-line no-underscore-dangle
delete L.Icon.Default.prototype._getIconUrl;

L.Icon.Default.mergeOptions({
  iconRetinaUrl: require('leaflet/dist/images/marker-icon-2x.png'),
  iconUrl: require('leaflet/dist/images/marker-icon.png'),
  shadowUrl: require('leaflet/dist/images/marker-shadow.png'),
});

const LeafletMapBasic = props => {
  const { latitude, longitude, width, height, zoom } = props;

  const position = [latitude, longitude];
  return (
    <GmapWraper width={width} height={height}>
      <MapContainer center={position} zoom={zoom}>
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
        <Marker position={position}>
          <Popup>
            A pretty CSS3 popup.
            <br />
            Easily customizable.
          </Popup>
        </Marker>
      </MapContainer>
    </GmapWraper>
  );
};
LeafletMapBasic.propTypes = {
  latitude: PropTypes.number,
  longitude: PropTypes.number,
  width: PropTypes.string,
  height: PropTypes.string,
  zoom: PropTypes.number,
};

const LeafletMapMultipleIcon = props => {
  const { latitude, longitude, width, height, zoom, data } = props;

  const position = [latitude, longitude];
  return (
    <GmapWraper width={width} height={height}>
      <MapContainer center={position} zoom={zoom}>
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
        {data.map(item => {
          return (
            <Marker key={item.id} position={item.position}>
              <Popup>
                A pretty CSS3 popup.
                <br />
                Easily customizable.
              </Popup>
            </Marker>
          );
        })}
      </MapContainer>
    </GmapWraper>
  );
};

LeafletMapMultipleIcon.propTypes = {
  latitude: PropTypes.number,
  longitude: PropTypes.number,
  width: PropTypes.string,
  height: PropTypes.string,
  zoom: PropTypes.number,
  data: PropTypes.arrayOf(PropTypes.object),
};

const LeafletMapCustomIcon = props => {
  const { latitude, longitude, width, height, zoom, faIcon } = props;
  const fontAwesomeIcon = L.divIcon({
    html: `<i style="color: #2880CA" class="${faIcon}"></i>`,
    iconSize: [20, 20],
    className: 'myDivIcon',
  });
  const position = [latitude, longitude];
  return (
    <GmapWraper width={width} height={height}>
      <MapContainer center={position} zoom={zoom}>
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
        <Marker position={position} icon={fontAwesomeIcon}>
          <Popup>
            A pretty CSS3 popup.
            <br />
            Easily customizable.
          </Popup>
        </Marker>
      </MapContainer>
    </GmapWraper>
  );
};
LeafletMapCustomIcon.propTypes = {
  latitude: PropTypes.number,
  longitude: PropTypes.number,
  width: PropTypes.string,
  height: PropTypes.string,
  zoom: PropTypes.number,
  faIcon: PropTypes.string,
};

const LeafletMarkerCluster = props => {
  const { latitude, longitude, width, height, zoom, data } = props;

  const position = [latitude, longitude];
  return (
    <GmapWraper width={width} height={height}>
      <MapContainer center={position} zoom={zoom} className="markercluster-map" maxZoom={18}>
        <TileLayer
          url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
          attribution='&copy; <a href="http://osm.org/copyright">OpenStreetMap</a> contributors'
        />
        <MarkerClusterGroup>
          {data.map(item => {
            return (
              <Marker key={item.id} position={item.position}>
                <Popup>
                  A pretty CSS3 popup.
                  <br />
                  Easily customizable.
                </Popup>
              </Marker>
            );
          })}
        </MarkerClusterGroup>
      </MapContainer>
    </GmapWraper>
  );
};

LeafletMarkerCluster.propTypes = {
  latitude: PropTypes.number,
  longitude: PropTypes.number,
  width: PropTypes.string,
  height: PropTypes.string,
  zoom: PropTypes.number,
  data: PropTypes.arrayOf(PropTypes.object),
};

export { LeafletMapBasic, LeafletMapMultipleIcon, LeafletMapCustomIcon, LeafletMarkerCluster };

// hexadash-vue/full-version/src/view/maps/Leaflet.vue
<template>
  <div>
    <sdPageHeader title="Leaflet Map" class="ninjadash-page-header-main">

    </sdPageHeader>
    <Main>
      <a-row :gutter="25">
        <a-col :md="12" :xs="24">
          <sdCards title="Leaflet Basic Map">
            <l-map
              :center="[50.797897, -1.077641]"
              :zoom="15"
              class="map-wrapper"
            >
              <l-tile-layer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              >
              </l-tile-layer>
              <l-marker :lat-lng="[50.797897, -1.077641]"></l-marker>
            </l-map>
          </sdCards>
        </a-col>
        <a-col :md="12" :xs="24">
          <sdCards title="Leaflet MultipleIcon Map">
            <l-map
              :center="[50.797897, -1.077641]"
              :zoom="12"
              class="map-wrapper"
            >
              <l-tile-layer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              >
              </l-tile-layer>
              <l-marker
                v-for="item in place"
                :key="item.id"
                :lat-lng="item.position"
              ></l-marker>
            </l-map>
          </sdCards>
        </a-col>
        <a-col :md="24" :xs="24">
          <sdCards title="Leaflet Custom Icon Map">
            <l-map
              :center="[50.797897, -1.077641]"
              :zoom="12"
              class="map-wrapper"
            >
              <l-tile-layer
                url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"
              >
              </l-tile-layer>
              <l-marker
                :icon="fontAwesomeIcon"
                :lat-lng="[50.797897, -1.077641]"
              ></l-marker>
            </l-map>
          </sdCards>
        </a-col>
      </a-row>
    </Main>
  </div>
</template>

<script>
import { Main } from "../styled";
import L, { Icon, latLng } from "leaflet";
import { defineComponent } from "vue";

delete Icon.Default.prototype._getIconUrl;
Icon.Default.mergeOptions({
  iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
  iconUrl: require("leaflet/dist/images/marker-icon.png"),
  shadowUrl: require("leaflet/dist/images/marker-shadow.png"),
});

const fontAwesomeIcon = L.divIcon({
  html: `<i style="color: #2880CA" class="fa fa-thumb-tack fa-3x"></i>`,
  iconSize: [20, 20],
  className: "myDivIcon",
});

export default defineComponent({
  name: "Leaflet",
  components: {
    Main,
  },
  data() {
    return {
      center: latLng(50.797897, -1.077641),
      latLng: latLng(50.797897, -1.077641),
      fontAwesomeIcon,
      baseUrl: "http://mesonet.agron.iastate.edu/cgi-bin/wms/nexrad/n0r.cgi",
      layers: [
        {
          name: "Weather Data",
          visible: true,
          format: "image/png",
          layers: "nexrad-n0r-900913",
          transparent: true,
          attribution: "Weather data © 2012 IEM Nexrad",
        },
      ],
      place: [
        {
          id: 1,
          position: [50.797897, -1.077641],
        },
        {
          id: 2,
          position: [50.798897, -1.013641],
        },
        {
          id: 3,
          position: [50.7997799, -1.100641],
        },
      ],
    };
  },
});
</script>

<style scoped>
.map-wrapper {
  height: 600px !important;
}
</style>
