// hexadash-typescript-vue/documentation/src/components/buttons/ShareButton.vue
<template>
  <sdPopover placement="bottomLeft" action="click">
    <template v-slot:content>
      <a to="#">
        <unicon name="facebook-f"></unicon>
        <span>Facebook</span>
      </a>
      <a to="#">
        <unicon name="twitter-alt"></unicon>
        <span>Twitter</span>
      </a>
      <a to="#">
        <unicon name="rss"></unicon>
        <span>Feed</span>
      </a>
      <a to="#">
        <unicon name="linkedin"></unicon>
        <span>Linkedin</span>
      </a>
      <a to="#">
        <unicon name="instagram"></unicon>
        <span>Instagram</span>
      </a>
    </template>
    <sdButton size="small" type="white">
      <unicon name="share-alt" width="14"></unicon>
      <span>Share</span>
    </sdButton>
  </sdPopover>
</template>

<script>
import { defineComponent } from "vue";
export default defineComponent({
  name: "ShareButton",
  components: {},
});
</script>

// hexadash-react-tailwind/documentation/src/components/buttons/share-button/share-button.js
import React from 'react';
import { NavLink } from 'react-router-dom';
import UilFacebook from '@iconscout/react-unicons/icons/uil-facebook-f';
import UilTwitter from '@iconscout/react-unicons/icons/uil-twitter';
import UilRss from '@iconscout/react-unicons/icons/uil-rss';
import UilLinkedin from '@iconscout/react-unicons/icons/uil-linkedin';
import UilInstagram from '@iconscout/react-unicons/icons/uil-instagram';
import UilShareAlt from '@iconscout/react-unicons/icons/uil-share-alt';
import { Popover } from '../../popup/popup';
import { Button } from '../buttons';

const ShareButtonPageHeader = () => {
  const content = (
    <>
      <NavLink to="#">
        <UilFacebook />
        <span>Facebook</span>
      </NavLink>
      <NavLink to="#">
        <UilTwitter />
        <span>Twitter</span>
      </NavLink>
      <NavLink to="#">
        <UilRss />
        <span>Feed</span>
      </NavLink>
      <NavLink to="#">
        <UilLinkedin />
        <span>Linkedin</span>
      </NavLink>
      <NavLink to="#">
        <UilInstagram />
        <span>Instagram</span>
      </NavLink>
    </>
  );
  return (
    <Popover placement="bottomLeft" content={content} trigger="click">
      <Button size="small" type="white" key="3">
        <UilShareAlt />
        Share
      </Button>
    </Popover>
  );
};

export { ShareButtonPageHeader };
