// hexadash-react/documentation/src/container/forms/FormLayout.js
import { Col, Row } from 'antd';
import { PageHeader } from '../../components/page-headers/page-headers';
import { Main } from '../styled';
import { HorizontalForm } from './overview/HorizontalForm';
import { HorizontalIconForm } from './overview/HorizontalIconForm';

const FormLayout = () => {
  const PageRoutes = [
    {
      path: 'index',
      breadcrumbName: 'Dashboard',
    },
    {
      path: 'first',
      breadcrumbName: 'Form Layouts',
    },
  ];
  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Form Layouts" routes={PageRoutes} />
      <Main>
        <Row gutter={25}>
          <Col xs={24}>
            <HorizontalForm />
          </Col>
          <Col xs={24}>
            <HorizontalIconForm />
          </Col>
        </Row>
      </Main>
    </>
  );
};

export default FormLayout;

// hexadash-vue/full-version/src/view/forms/FormLayout.vue
<template>
  <div>
    <sdPageHeader title="Form Layout" class="ninjadash-page-header-main">

    </sdPageHeader>
    <Main>
      <a-row :gutter="25">
        <a-col :lg="12" :xs="24">
          <HorizontalForm />
        </a-col>
        <a-col :lg="12" :xs="24">
          <HorizontalIconForm />
        </a-col>
        <a-col :lg="12" :xs="24">
          <VerticalForm />
        </a-col>
        <a-col :lg="12" :xs="24">
          <VerticalIconForm />
        </a-col>
        <a-col :xs="24">
          <MultiColumnForm />
        </a-col>
      </a-row>
    </Main>
  </div>
</template>

<script>
import { Main } from "../styled";
import HorizontalForm from "./overview/HorizontalForm";
import HorizontalIconForm from "./overview/HorizontalIconForm";
import VerticalForm from "./overview/VerticalForm";
import VerticalIconForm from "./overview/VerticalIconForm";
import MultiColumnForm from "./overview/MultiColumnForm";
import { defineComponent } from "vue";
export default defineComponent({
  name: "Form",
  components: {
    Main,
    HorizontalForm,
    HorizontalIconForm,
    VerticalForm,
    VerticalIconForm,
    MultiColumnForm,
  },
});
</script>
