// hexadash-react/documentation/src/components/utilities/auth-info/Search.js
import React, { useState } from 'react';
import UilSearch from '@iconscout/react-unicons/icons/uil-search';
import UilTimes from '@iconscout/react-unicons/icons/uil-times';
import { Link } from 'react-router-dom';
import { Form, Input } from 'antd'
import PropTypes from 'prop-types';
// import { useSelector } from 'react-redux';

const SearchBar = React.memo(() => {
    const [form] = Form.useForm();
    // const { rtl } = useSelector(state => {
    //     return {
    //         rtl: state.ChangeLayoutMode.rtlData,
    //     };
    // });

    const [state, setState] = useState({
        openSearch: false
    });

    const openSearchbar = (e) => {
        e.preventDefault();
        setState({
            ...state,
            openSearch: true,
        });
    };
    const closeSearchbar = (e) => {
        e.preventDefault();
        setState({
            ...state,
            openSearch: false,
        });
    };

    const { openSearch } = state;

    return (
        <div className={openSearch ? 'ninjadash-nav-actions__item ninjadash-nav-actions__searchbar show' : 'ninjadash-nav-actions__item ninjadash-nav-actions__searchbar'}>
            <div className="ninjadash-searchbar">
                <Form form={form} name="ninjadash-search">
                    <Form.Item name="search-input">
                        <Input placeholder="Search Here" />
                    </Form.Item>
                </Form>
            </div>
            <Link to="/" onClick={e => openSearchbar(e)} className="ninjadash-search-icon"><UilSearch /></Link>
            <Link to="/" onClick={e => closeSearchbar(e)} className="ninjadash-close-icon"><UilTimes /></Link>
        </div>
    );
});

SearchBar.propTypes = {
    rtl: PropTypes.bool,
};

export default SearchBar;

// hexadash-vue/documentation/src/components/utilities/auth-info/Search.vue
<template>
  <div
    :class="
      openSearch
        ? 'ninjadash-nav-actions__item ninjadash-nav-actions__searchbar show'
        : 'ninjadash-nav-actions__item ninjadash-nav-actions__searchbar'
    "
  >
    <div class="ninjadash-searchbar">
      <a-form name="ninjadash-search" id="ninjadash-search">
        <a-form-item name="search-input">
          <a-input placeholder="Search Here" />
        </a-form-item>
      </a-form>
    </div>
    <router-link
      to="#"
      @click="(e) => openSearchBar(e)"
      class="ninjadash-search-icon"
      ><unicon name="search"></unicon
    ></router-link>
    <router-link
      to="#"
      @click="(e) => closeSearchBar(e)"
      class="ninjadash-close-icon"
    >
      <unicon name="times"></unicon>
    </router-link>
  </div>
</template>
<script>
import { defineComponent, ref } from "vue";
export default defineComponent({
  name: "SearchBar",
  setup() {
    const openSearch = ref(false);
    const openSearchBar = (e) => {
      e.preventDefault();
      openSearch.value = true;
    };
    const closeSearchBar = (e) => {
      e.preventDefault();
      openSearch.value = false;
    };
    return {
      openSearch,
      openSearchBar,
      closeSearchBar,
    };
  },
});
</script>
