// hexadash-react/documentation/src/container/pages/Auth0.js
import { Col, Row } from 'antd';
import Prism from "prismjs";
import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { Cards } from '../../components/cards/frame/cards-frame';
import { PageHeader } from '../../components/page-headers/page-headers';
import { Main } from '../styled';
import { DocumentationStyleWrap } from './style';

const Auth0 = () => {
  const PageRoutes = [
    {
        path: 'index',
        breadcrumbName: 'Docs',
    },
    {
        path: '',
        breadcrumbName: 'Auth0 Integration',
    },
  ];
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Auth0 Integration" routes={PageRoutes} />
      <Main>
        <DocumentationStyleWrap>
          <Row gutter={25}>
            <Col md={18} xs={24}>
              <Cards headless>
                <div className="ninjadash-template-documentation">
                    <h2>Auth0 Configuration</h2>
                    <p className="mb-0">To configure Auth0, find the .env file and change the configuration shown in the image below</p>
                    <div className="docs-highlighter mb-35">
                        <pre>
                            <code className="language-javascript">
{
`
import actions from './actions';
import { DataService } from '../../../config/dataService/dataService';
`
}
                            </code>
                        </pre>
                    </div>
                    <p>For more information go to <Link to="/">https://auth0.com/</Link></p>
                </div>
              </Cards>
            </Col>
          </Row>
        </DocumentationStyleWrap>
        
      </Main>
    </>
  );
};

export default Auth0;

// hexadash-vue/documentation/src/view/pages/Auth0.vue
<template>
  <div>
    <sdPageHeader
      title="Auth0 Integration"
      class="ninjadash-page-header-main"
      :routes="PageRoutes"
    >
    </sdPageHeader>
    <Main>
      <DocumentationStyleWrap>
        <a-row :gutter="25">
          <a-col :sm="24" :xs="24">
            <sdCards headless>
              <div class="ninjadash-template-documentation">
                <h2>Auth0 Configuration</h2>
                <p class="mb-0">
                  To configure Auth0, find the .env file and change the
                  configuration shown in the image below
                </p>

                <prism-editor
                  :readonly="false"
                  class="my-editor height-100 mb-35"
                  v-model="auth0Env"
                  :highlight="highlighter"
                ></prism-editor>

                <p>
                  For more information go to
                  <a href="https://auth0.com/" target="_blank"
                    >https://auth0.com/</a
                  >
                </p>
              </div>
            </sdCards>
          </a-col>
        </a-row>
      </DocumentationStyleWrap>
    </Main>
  </div>
</template>

<script>
import { Main } from "../styled";
import { defineComponent, ref } from "vue";
import { DocumentationStyleWrap } from "./style";

import { PrismEditor } from "vue-prism-editor";
import "vue-prism-editor/dist/prismeditor.min.css";
import { highlight, languages } from "prismjs/components/prism-core";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-javascript";
import "prismjs/themes/prism-tomorrow.css";

const PageRoutes = [
  {
    path: "index",
    breadcrumbName: "Docs",
  },
  {
    path: "",
    breadcrumbName: "Firebase Integration",
  },
];

export default defineComponent({
  name: "Firebase",
  components: {
    Main,
    DocumentationStyleWrap,
    PrismEditor,
  },
  setup() {
    const auth0Env = ref(`  
VUE_APP_AUTH0_DOMAIN='auth domain'
VUE_APP_AUTH0_CLIENT_ID='client id'
    `);

    return {
      PageRoutes,
      auth0Env,
    };
  },
  methods: {
    highlighter(code) {
      return highlight(code, languages.js); //returns html
    },
  },
});
</script>
