// hexadash-vue/documentation/src/components/pageHeaders/PageHeaders.vue
<script>
import { PageHeaderStyle } from "./style";
import VueTypes from "vue-types";
import { defineComponent } from "vue";

export const PageHeader = defineComponent({
  components: {
    PageHeaderStyle,
  },
  props: {
    title: VueTypes.oneOfType([VueTypes.string, VueTypes.object]),
    subTitle: VueTypes.oneOfType([VueTypes.string, VueTypes.object]),
    bgColor: VueTypes.string,
    class: VueTypes.string,
    routes: VueTypes.array.def([
      {
        path: "index",
        breadcrumbName: "Dashboard",
      },
      {
        path: "course",
        breadcrumbName: "Courses",
      },
    ]),
    buttons: VueTypes.array,
    ghost: VueTypes.bool,
    breadcrumb: VueTypes.object,
  },

  render() {
    return (
      <div>
        <div
          style={
            {
              // backgroundColor: this.bgColor || "#F4F5F7",
            }
          }
        >
          <PageHeaderStyle
            class={this.class}
            title={this.title || this.$slots.title()}
            subTitle={
              this.subTitle ||
              (this.$slots.subTitle ? this.$slots.subTitle() : null)
            }
            breadcrumb={this.routes.length && { routes: this.routes }}
            ghost={this.ghost}
            extra={this.$slots.buttons && this.$slots.buttons()}
          ></PageHeaderStyle>
        </div>
      </div>
    );
  },
});

export default PageHeader;
</script>

// hexadash-react-tailwind/documentation/src/components/page-headers/page-headers.js
import React from 'react';
import PropTypes from 'prop-types';
import { HeaderWrapper, PageHeaderStyle } from './style';
import { Breadcrumb } from 'antd';
import { Link } from 'react-router-dom';

const PageHeader = props => {
  const { title, subTitle, routes, buttons, ghost, bgColor, className } = props;
  const breadcrumb = (
    routes ? 
    <Breadcrumb>
        {routes.map((route,index) => (index + 1) === routes.length ? <Breadcrumb.Item key={index}>{route.breadcrumbName }</Breadcrumb.Item>:<Breadcrumb.Item key={index}><Link to={route.path}>{route.breadcrumbName }</Link></Breadcrumb.Item>)}
    </Breadcrumb>
    :''
  )
  return (
    <>
      <HeaderWrapper bgColor={bgColor}>
        <PageHeaderStyle
          className={className}
          title={title}
          subTitle={subTitle}
          breadcrumb={breadcrumb}
          extra={buttons}
          ghost={ghost}
        />
      </HeaderWrapper>
    </>
  );
};

PageHeader.propTypes = {
  title: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  subTitle: PropTypes.oneOfType([PropTypes.string, PropTypes.object]),
  bgColor: PropTypes.string,
  className: PropTypes.string,
  routes: PropTypes.arrayOf(PropTypes.object),
  buttons: PropTypes.array,
  ghost: PropTypes.bool,
};

export { PageHeader };
