// hexadash-vue/full-version/src/view/forms/FormElements.vue
<template>
  <div>
    <sdPageHeader title="Form Elements" class="ninjadash-page-header-main">

    </sdPageHeader>
    <Main>
      <a-row :gutter="25">
        <a-col :xs="24">
          <GridForm />
        </a-col>
        <a-col :lg="12" :xs="24">
          <SizedForm />
          <InputForm />
        </a-col>
        <a-col :lg="12" :xs="24">
          <sdCards title="Text Input" class="mb-25">
            <a-form name="ninjadash_textarea" layout="vertical">
              <a-form-item name="basic-textarea" label="Basic Textarea">
                <a-textarea placeholder="Basic usage" :rows="2" />
              </a-form-item>
              <a-form-item label="Unresizable Textarea">
                <a-textarea
                  placeholder="Unresizable Textarea"
                  name="unresizable-textarea"
                  class="ninjadash_unresizable"
                  :rows="3"
                />
              </a-form-item>
            </a-form>
          </sdCards>
          <sdCards title="Select" class="mb-25">
            <a-form name="ninjadash_Select" layout="vertical">
              <a-form-item label="Basic Select">
                <a-select
                  size="large"
                  name="basic-select"
                  class="ninjadash_fullwidth-select"
                >
                  <a-select-option value="1">1</a-select-option>
                  <a-select-option default-value="2" value="2"
                    >2</a-select-option
                  >
                  <a-select-option value="3">3</a-select-option>
                  <a-select-option value="4">4</a-select-option>
                </a-select>
              </a-form-item>
              <a-form-item label="Disabled Basic Select">
                <a-select
                  size="large"
                  name="disabled-select"
                  class="ninjadash_fullwidth-select"
                  disabled
                >
                  <a-select-option value="1">1</a-select-option>
                </a-select>
              </a-form-item>
              <a-form-item label="Multiple Select">
                <a-select
                  mode="multiple"
                  :default-value="['1', '2']"
                  placeholder="Please select"
                >
                  <a-select-option value="1">1</a-select-option>
                  <a-select-option value="2">2</a-select-option>
                  <a-select-option value="3">3</a-select-option>
                  <a-select-option value="4">4</a-select-option>
                </a-select>
              </a-form-item>
              <a-form-item label="Disabled Multiple Select">
                <a-select
                  mode="multiple"
                  :default-value="['1', '2']"
                  placeholder="Please select"
                  disabled
                >
                  <a-select-option value="1">1</a-select-option>
                  <a-select-option value="2">2</a-select-option>
                  <a-select-option value="3">3</a-select-option>
                  <a-select-option value="4">4</a-select-option>
                </a-select>
              </a-form-item>
            </a-form>
          </sdCards>
          <sdCards title="File Browser" class="ninjadash_upload-form mb-25">
            <a-form name="ninjadash_file_browser" layout="vertical">
              <a-upload
                class="ninjadash_upload-basic"
                name="file"
                :multiple="true"
                action="https://www.mocky.io/v2/5cc8019d300000980a055e76"
                :headers="headers"
                @change="handleChange"
              >
                <span class="ninjadash_upload-text">Select File</span>
                <a to="#" class="ninjadash_upload-browse"> Browse </a>
              </a-upload>
            </a-form>
          </sdCards>
          <CheckListWrap class="mb-25">
            <sdCards title="Checkboxes and Radios">
              <div class="ninjadash_check-list-wrap">
                <ul class="ninjadash_check-list ninjadash_check-list--left">
                  <li>
                    <a-checkbox>Checkbox</a-checkbox>
                  </li>
                  <li>
                    <a-checkbox checked> Checked </a-checkbox>
                  </li>
                  <li>
                    <a-checkbox disabled> Disabled Unchecked </a-checkbox>
                  </li>
                  <li>
                    <a-checkbox checked disabled> Disabled Checked </a-checkbox>
                  </li>
                </ul>
                <ul class="ninjadash_check-list ninjadash_check-list--right">
                  <li>
                    <a-radio>Uncheck</a-radio>
                  </li>
                  <li>
                    <a-radio checked>Checked</a-radio>
                  </li>
                  <li>
                    <a-radio disabled>Disabled Unchecked</a-radio>
                  </li>
                  <li>
                    <a-radio checked disabled> Disabled Checked </a-radio>
                  </li>
                </ul>
              </div>
            </sdCards>
          </CheckListWrap>
        </a-col>
      </a-row>
    </Main>
  </div>
</template>

<script>
import { message } from "ant-design-vue";
import { Main } from "../styled";
import { CheckListWrap } from "./overview/Style";
import GridForm from "./overview/GridForm";
import SizedForm from "./overview/SizedForm";
import InputForm from "./overview/InputForm";
import { ref, defineComponent } from "vue";
export default defineComponent({
  name: "FormElement",
  components: {
    Main,
    GridForm,
    SizedForm,
    InputForm,
    CheckListWrap,
  },
  setup() {
    const handleChange = (info) => {
      if (info.file.status !== "uploading") {
        console.log(info.file, info.fileList);
      }

      if (info.file.status === "done") {
        message.success(`${info.file.name} file uploaded successfully`);
      } else if (info.file.status === "error") {
        message.error(`${info.file.name} file upload failed.`);
      }
    };

    const fileList = ref([]);
    return {
      fileList,
      headers: {
        authorization: "authorization-text",
      },
      handleChange,
    };
  },
});
</script>

// hexadash-react-tailwind/documentation/src/container/forms/FormElements.js
import React from 'react';
import { Row, Col, Form, Input, Select, Upload, message, Radio, Checkbox } from 'antd';
import { Link } from 'react-router-dom';
import { GridForm } from './overview/GridForm';
import { SizedForm } from './overview/SizedForm';
import { InputForm } from './overview/InputForm';
import { CheckListWrap } from './overview/Style';
import { Main, BasicFormWrapper } from '../styled';
import { Cards } from '../../components/cards/frame/cards-frame';
import { PageHeader } from '../../components/page-headers/page-headers';

const { Option } = Select;
const { TextArea } = Input;
const props = {
  name: 'file',
  action: 'https://www.mocky.io/v2/5cc8019d300000980a055e76',
  headers: {
    authorization: 'authorization-text',
  },
  onChange(info) {
    if (info.file.status !== 'uploading') {
      // console.log(info.file, info.fileList);
    }
    if (info.file.status === 'done') {
      message.success(`${info.file.name} file uploaded successfully`);
    } else if (info.file.status === 'error') {
      message.error(`${info.file.name} file upload failed.`);
    }
  },
};
const FormElements = () => {
  const PageRoutes = [
    {
      path: 'index',
      breadcrumbName: 'Dashboard',
    },
    {
      path: 'first',
      breadcrumbName: 'Form Elements',
    },
  ];
  function onChange() {}
  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Form Elements" routes={PageRoutes} />
      <Main>
        <Row gutter={25}>
          <Col xs={24}>
            <GridForm />
          </Col>
          <Col lg={12} xs={24}>
            <SizedForm />
            <InputForm />
          </Col>
          <Col lg={12} xs={24}>
            <BasicFormWrapper>
              <Cards title="Text Input" className="mb-25">
                <Form name="ninjadash-textarea" layout="vertical">
                  <Form.Item name="basic-textarea" label="Basic Textarea">
                    <TextArea />
                  </Form.Item>
                  <Form.Item name="unresizable-textarea" label="Unresizable Textarea">
                    <TextArea className="ninjadash-unresizable" />
                  </Form.Item>
                </Form>
              </Cards>
            </BasicFormWrapper>
            <BasicFormWrapper>
              <Cards title="Select" className="mb-25">
                <Form name="ninjadash-select" layout="vertical">
                  <Form.Item name="basic-select" label="Basic Select">
                    <Select size="large" className="ninjadash-fullwidth-select">
                      <Option value="1">1</Option>
                      <Option value="2">2</Option>
                      <Option value="3">3</Option>
                    </Select>
                  </Form.Item>
                  <Form.Item name="disabled-select" label="Disabled Basic Select">
                    <Select size="large" className="ninjadash-fullwidth-select" disabled>
                      <Option value="1">1</Option>
                      <Option value="2">2</Option>
                      <Option value="3">3</Option>
                    </Select>
                  </Form.Item>
                  <Form.Item name="multi-select" initialValue={['1', '2']} label="Multiple Select">
                    <Select size="large" mode="multiple" className="ninjadash-fullwidth-select">
                      <Option value="1">1</Option>
                      <Option value="2">2</Option>
                      <Option value="3">3</Option>
                    </Select>
                  </Form.Item>
                  <Form.Item name="disabled-multi-select" initialValue={['1', '2']} label="Disabled Multiple Select">
                    <Select size="large" mode="multiple" className="ninjadash-fullwidth-select" disabled>
                      <Option value="1">1</Option>
                      <Option value="2">2</Option>
                      <Option value="3">3</Option>
                    </Select>
                  </Form.Item>
                </Form>
              </Cards>
            </BasicFormWrapper>
            <BasicFormWrapper>
              <Cards title="File Browser" className="ninjadash-upload-form mb-25">
                <Form name="ninjadash-upload" layout="vertical">
                  <Upload className="ninjadash-upload-basic" {...props}>
                    <span className="ninjadash-upload-text">Select File</span>
                    <Link to="#" className="ninjadash-upload-browse">
                      Browse
                    </Link>
                  </Upload>
                </Form>
              </Cards>
            </BasicFormWrapper>
            <CheckListWrap className="mb-25">
              <Cards title="Checkboxes and Radios">
                <div className="ninjadash-check-list-wrap">
                  <ul className="ninjadash-check-list ninjadash-check-list--left">
                    <li>
                      <Checkbox onChange={onChange}>Checkbox</Checkbox>
                    </li>
                    <li>
                      <Checkbox onChange={onChange} checked>
                        Checked
                      </Checkbox>
                    </li>
                    <li>
                      <Checkbox onChange={onChange} disabled>
                        Disabled Unchecked
                      </Checkbox>
                    </li>
                    <li>
                      <Checkbox onChange={onChange} checked disabled>
                        Disabled Checked
                      </Checkbox>
                    </li>
                  </ul>
                  <ul className="ninjadash-check-list ninjadash-check-list--right">
                    <li>
                      <Radio>Uncheck</Radio>
                    </li>
                    <li>
                      <Radio checked>Checked</Radio>
                    </li>
                    <li>
                      <Radio disabled>Disabled Unchecked</Radio>
                    </li>
                    <li>
                      <Radio checked disabled>
                        Disabled Checked
                      </Radio>
                    </li>
                  </ul>
                </div>
              </Cards>
            </CheckListWrap>
          </Col>
        </Row>
      </Main>
    </>
  );
};

export default FormElements;
