// hexadash-vue/full-version/src/view/forms/overview/MultiColumnForm.vue
<template>
  <div>
    <BasicFormWrapper class="mb-25">
      <sdCards title="Multiple Column">
        <a-form name="multi-form" layout="vertical">
          <a-row :gutter="30">
            <a-col :sm="12" :xs="24" class="mb-25">
              <a-form-item>
                <a-input placeholder="Username" />
              </a-form-item>
              <a-form-item>
                <a-input placeholder="City" />
              </a-form-item>
              <a-form-item>
                <a-input placeholder="Company" />
              </a-form-item>
            </a-col>
            <a-col :sm="12" :xs="24" class="mb-25">
              <a-form-item>
                <a-input placeholder="Last Name" />
              </a-form-item>
              <a-form-item>
                <a-input placeholder="Country" />
              </a-form-item>
              <a-form-item>
                <a-input placeholder="Email" />
              </a-form-item>
            </a-col>
          </a-row>
          <a-row>
            <a-col :sm="12" :xs="24">
              <div class="ninjadash_form-action">
                <sdButton
                  class="btn-signin"
                  html-type="submit"
                  type="light"
                  style="margin-right: 15px"
                >
                  Cancel
                </sdButton>
                <sdButton class="btn-signin" type="primary"> Save </sdButton>
              </div>
            </a-col>
          </a-row>
        </a-form>
      </sdCards>
    </BasicFormWrapper>
  </div>
</template>

<script>
import { BasicFormWrapper } from "../../styled";
import { defineComponent } from "vue";
export default defineComponent({
  name: "MultiColumnForm",
  components: {
    BasicFormWrapper,
  },
});
</script>

// hexadash-react/documentation/src/container/forms/overview/MultiColumnForm.js
import React from 'react';
import { Row, Col, Form, Input, Button } from 'antd';
import { Cards } from '../../../components/cards/frame/cards-frame';
import { BasicFormWrapper } from '../../styled';

const MultiColumnForm = () => {
  return (
    <BasicFormWrapper className="mb-25">
      <Cards title="Multiple Column">
        <Form name="multi-form" layout="horizontal">
          <Row gutter={30}>
            <Col sm={12} xs={24} className="mb-25">
              <Form.Item name="sDash_f-name">
                <Input placeholder="First Name" />
              </Form.Item>
              <Form.Item name="sDash_city">
                <Input placeholder="City" />
              </Form.Item>
              <Form.Item name="sDash_company">
                <Input placeholder="Company" />
              </Form.Item>
            </Col>
            <Col sm={12} xs={24} className="mb-25">
              <Form.Item name="sDash_l-name">
                <Input placeholder="Last Name" />
              </Form.Item>
              <Form.Item name="sDash_country">
                <Input placeholder="Country" />
              </Form.Item>
              <Form.Item name="sDash_email">
                <Input placeholder="Email" />
              </Form.Item>
            </Col>
          </Row>
          <Row>
            <Col sm={12} xs={24}>
              <div className="ninjadash-form-action">
                <Button className="btn-signin" htmlType="submit" type="light" size="large">
                  Cancel
                </Button>
                <Button className="btn-signin" type="primary" size="large">
                  Save
                </Button>
              </div>
            </Col>
          </Row>
        </Form>
      </Cards>
    </BasicFormWrapper>
  );
};

export { MultiColumnForm };
