// hexadash-react-tailwind/documentation/src/container/pages/Navigation.js
import { Col, Row } from 'antd';
import Prism from "prismjs";
import { useEffect } from 'react';
import { Cards } from '../../components/cards/frame/cards-frame';
import { PageHeader } from '../../components/page-headers/page-headers';
import { Main } from '../styled';
import { DocumentationStyleWrap } from './style';

const Navigation = () => {
  const PageRoutes = [
    {
        path: 'index',
        breadcrumbName: 'Docs',
    },
    {
        path: '',
        breadcrumbName: 'Routing',
    },
  ];
  useEffect(() => {
    Prism.highlightAll();
  }, []);
  return (
    <>
      <PageHeader className="ninjadash-page-header-main" title="Routing" routes={PageRoutes} />
      <Main>
        <DocumentationStyleWrap>
          <Row gutter={25}>
            <Col md={18} xs={24}>
              <Cards headless>
                <div className="ninjadash-template-documentation">
                    <p>Left sidebar Cutomization is very easy. If you want add, remove or edit manu item form sidebar, please follow below instructions.  </p>
                    <h2>How add item to Sidebar ?</h2>
                    <div className="docs-highlighter">
                        <p className="mb-5">For Sidebar wee need to update our menu object from <code>src/layout/MenuItems.js</code></p>
                        <pre>
                            <code className="language-javascript">
{
`
const items = [
  getItem(
    <NavLink onClick={toggleCollapsed} to={"PATH"}>
      MENU LABEL
    </NavLink>, 
    'MENU ID', 
    !topMenu && <ICON />),
];
`
}
                            </code>
                        </pre>
                    </div>
                    <div className="docs-highlighter">
                        <p className="mb-5">Then assign the items to Menu component</p>
                        <pre>
                            <code className="language-javascript">
{
`
import { Menu } from 'antd';
const MenuItems = () => {
  return (
    <Menu
      mode='inline'
      overflowedIndicator={<ICON />}
      items={items}
    />
  );
};

export default MenuItems;
`
}
                            </code>
                        </pre>
                    </div>
                </div>
              </Cards>
            </Col>
          </Row>
        </DocumentationStyleWrap>
        
      </Main>
    </>
  );
};

export default Navigation;

// hexadash-typescript-vue/documentation/src/view/pages/Navigation.vue
<template>
  <div>
    <sdPageHeader
      title="Navigation"
      class="ninjadash-page-header-main"
      :routes="PageRoutes"
    >
    </sdPageHeader>
    <Main>
      <DocumentationStyleWrap>
        <a-row :gutter="25">
          <a-col :sm="24" :xs="24">
            <sdCards headless>
              <div class="ninjadash-template-documentation">
                <p>
                  Left sidebar Customization is very easy. If you want add,
                  remove or edit menu item form sidebar, please follow below
                  instructions.
                </p>
                <h2>How Add Menu ?</h2>
                <p>We can find our menu</p>

                <prism-editor
                  :readonly="true"
                  class="my-editor height-100"
                  v-model="htmlPage"
                  :highlight="highlighter"
                ></prism-editor>
              </div>
            </sdCards>
          </a-col>
        </a-row>
      </DocumentationStyleWrap>
    </Main>
  </div>
</template>

<script>
import { Main } from "../styled";
import { defineComponent, ref } from "vue";

import { PrismEditor } from "vue-prism-editor";
import "vue-prism-editor/dist/prismeditor.min.css";
import { highlight, languages } from "prismjs/components/prism-core";
import "prismjs/components/prism-clike";
import "prismjs/components/prism-javascript";
import "prismjs/themes/prism-tomorrow.css";
import { DocumentationStyleWrap } from "./style";

const PageRoutes = [
  {
    path: "index",
    breadcrumbName: "Docs",
  },
  {
    path: "",
    breadcrumbName: "Navigation",
  },
];

export default defineComponent({
  name: "Navigation",
  components: {
    Main,
    PrismEditor,
    DocumentationStyleWrap,
  },
  setup() {
    const htmlPage = ref(`
<template>
  <a-menu
    :open-keys="openKeys"
  >
    <a-menu-item @click="toggleCollapsed" key="new-page">
      <template #icon>
        <unicon name="circle"></unicon>
      </template>
      <router-link to="/new-page"> New Page </router-link>
    </a-menu-item>

    <a-sub-menu key="dashboard">
      <template #icon>
        <unicon name="create-dashboard"></unicon>
      </template>
      <template #title>Dashboard</template>
      <a-menu-item @click="toggleCollapsed" key="demo-one">
        <router-link to="/demo-one"> Demo 1 </router-link>
      </a-menu-item>
    </a-sub-menu>
  </a-menu>
</template>

`);

    return {
      htmlPage,
      PageRoutes,
    };
  },
  methods: {
    highlighter(code) {
      return highlight(code, languages.js); //returns html
    },
  },
});
</script>
