// hexadash-vue/full-version/src/view/pages/blog/BlogDetails.vue
<template>
  <sdPageHeader
    title="Blog Details"
    :routes="pageRoutes"
    class="ninjadash-page-header-main"
  ></sdPageHeader>

  <Main>
    <a-row justify="center">
      <a-col :lg="15">
        <BlogDetailsStyle>
          <div class="ninjadash-blog-details">
            <div class="ninjadash-blog-featured-img">
              <img
                :src="require(`@/static/img/blogs/blog-details/1.png`)"
                alt="ninjadash Blog"
              />
            </div>
            <div class="ninjadash-blog-content-box">
              <div class="ninjadash-blog-content">
                <h1 class="ninjadash-blog-title">
                  Know More About Time Management System on your Daily Works
                </h1>
                <ul class="ninjadash-blog-meta">
                  <li class="ninjadash-blog-meta__author">
                    <img
                      :src="require(`@/static/img/users/1.png`)"
                      alt="ninjadash blog author"
                    />
                    <span class="ninjadash-blog-authorname">Charli Day</span>
                  </li>
                  <li class="ninjadash-blog-meta__date">01 July 2020</li>
                  <li class="ninjadash-blog-meta__category">
                    <router-link to="#">Development</router-link>
                  </li>
                  <li class="ninjadash-blog-meta__read-time">6 mins read</li>
                </ul>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter – not harder – so that
                  you get more done in less time, even when time is tight and
                  pressures are high. Failing to manage your time damages your
                  effectiveness and causes stress.
                </p>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter – not harder – so that
                  you get more done enables you to work smarter.
                </p>
                <h2>What is Time Management?</h2>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter – not harder – so that
                  you get more done in less time, even when time is tight and
                  pressures are high. Failing to manage your time damages your
                  effectiveness and causes stress.
                </p>
                <img
                  :src="require(`@/static/img/blogs/blog-details/2.png`)"
                  alt="ninjadash Blog"
                />
                <h3>How Can you Use your Time Properly?</h3>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter – not harder – so that
                  you get more done in less time, even when time is tight and
                  pressures are high
                </p>
                <blockquote>
                  <div class="ninjadash-blog-blockquote">
                    <p>
                      <img
                        class="ninjadash-blog-blockquote-icon-left"
                        :src="require(`@/static/img/icon/quote-left.png`)"
                        alt="ninjadash blockquote"
                      />
                      Usability design is to improve the usability of a product,
                      which is an important part to guide the actual design. It
                      can also be regarded. A month ago, I agreed to
                      <img
                        class="ninjadash-blog-blockquote-icon-right"
                        :src="require(`@/static/img/icon/quote-right.png`)"
                        alt="ninjadash blockquote"
                      />
                    </p>
                    <span class="ninjadash-blog-quote-author"
                      ><strong>Daniel Brown,</strong>Founder of Company</span
                    >
                  </div>
                </blockquote>
                <h4>Value of Time Management</h4>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter.
                </p>
                <ul class="ninjadash-blog-list">
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--label"
                      >Trim transparent pixels on exports:</span
                    >
                    <span class="ninjadash-blog-list__item--text"
                      >Usability design is to improve the usability of a
                      product, which is an important.</span
                    >
                  </li>
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--label"
                      >Crash and bug fixes:</span
                    >
                    <span class="ninjadash-blog-list__item--text"
                      >Usability design is to improve the usability of a
                      product, which is an important part to guide.</span
                    >
                  </li>
                </ul>
                <h5>How Can you Benefit from Time Management System?</h5>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter.
                </p>
                <ul class="ninjadash-blog-list">
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--text"
                      >Only be run by an explicit user action</span
                    >
                  </li>
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--text"
                      >Show UI in a single plugin-specific dialog</span
                    >
                  </li>
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--text"
                      >Make a technology change (described in the next section)
                      that avoided the privately-disclosed
                      vulnerabilities.</span
                    >
                  </li>
                </ul>
                <h5>Help Users Fill in Forms</h5>
                <p>
                  ”Time management” is the process of organizing and planning
                  how to divide your time between specific activities. Good time
                  management enables you to work smarter..
                </p>
                <ul class="ninjadash-blog-list">
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--text"
                      >Only be run by an explicit user action</span
                    >
                  </li>
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--text"
                      >Show UI in a single plugin-specific dialog</span
                    >
                  </li>
                  <li class="ninjadash-blog-list__item">
                    <span class="ninjadash-blog-list__item--text"
                      >Make a technology change (described in the next section)
                      that avoided the privately-disclosed
                      vulnerabilities.</span
                    >
                  </li>
                </ul>
              </div>
              <ul class="ninjadash-category-list">
                <li class="ninjadash-category-list__item">
                  <router-link to="#">Design Process</router-link>
                </li>
                <li class="ninjadash-category-list__item">
                  <router-link to="#">Prototype</router-link>
                </li>
                <li class="ninjadash-category-list__item">
                  <router-link to="#">Design Process</router-link>
                </li>
                <li class="ninjadash-category-list__item">
                  <router-link to="#">Prototype</router-link>
                </li>
              </ul>
              <ul class="ninjadash-social-links">
                <li>Share this article:</li>
                <li>
                  <router-link to="#" class="ninjadash-facebook">
                    <unicon name="facebook-f"></unicon>
                    <span>Share</span>
                  </router-link>
                </li>
                <li>
                  <router-link to="#" class="ninjadash-twitter">
                    <unicon name="twitter"></unicon>
                    <span>Tweet</span>
                  </router-link>
                </li>
                <li>
                  <router-link to="#" class="ninjadash-linkedin">
                    <unicon name="linkedin"></unicon>
                    <span>Share</span>
                  </router-link>
                </li>
                <li>
                  <router-link to="#" class="ninjadash-copy">
                    <unicon name="link-h"></unicon>
                    <span>Copy</span>
                  </router-link>
                </li>
              </ul>
              <div class="ninjadash-blog-author-box">
                <div class="ninjadash-blog-author-img">
                  <img
                    :src="require(`@/static/img/users/1.png`)"
                    alt="ninjadash Blog"
                  />
                </div>
                <div class="ninjadash-blog-author-info">
                  <span>Written By</span>
                  <span class="ninjadash-blog-author-name">Charli Day</span>
                  <p>
                    Charli Day is a British writer and social media manager
                    specializing in dynamic branding, campaign strategy and
                    content engagement.
                  </p>
                </div>
              </div>
              <div
                :class="
                  shareLinks
                    ? 'ninjadash-share-links show'
                    : 'ninjadash-share-links'
                "
              >
                <span>Share</span>
                <ul>
                  <li>
                    <router-link to="#" class="ninjadash-facebook"
                      ><unicon name="facebook-f"></unicon>
                    </router-link>
                  </li>
                  <li>
                    <router-link to="#" class="ninjadash-twitter"
                      ><unicon name="twitter"></unicon>
                    </router-link>
                  </li>
                  <li>
                    <router-link to="#" class="ninjadash-linkedin"
                      ><unicon name="linkedin"></unicon>
                    </router-link>
                  </li>
                  <li>
                    <router-link to="#" class="ninjadash-link"
                      ><unicon name="link-h"></unicon>
                    </router-link>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </BlogDetailsStyle>
      </a-col>
    </a-row>
  </Main>
</template>
<script>
import { Main } from "../../styled";
import { defineComponent, onMounted, ref } from "vue";
import cardData from "@/demoData/sampleCards.json";
import { BlogDetailsStyle } from "./Style";

const pageRoutes = [
  {
    path: "index",
    breadcrumbName: "Dashboard",
  },
  {
    path: "details",
    breadcrumbName: "Blog details",
  },
];

const Blog3 = defineComponent({
  name: "Blog3",
  components: {
    Main,
    BlogDetailsStyle,
  },
  setup() {
    const BlogCardData = cardData.BlogCardData.slice(0, 9);

    let shareLinks = ref(false);
    function updateShareLinksStat() {
      if (window.pageYOffset >= 600) {
        shareLinks.value = true;
      } else {
        shareLinks.value = false;
      }
    }
    onMounted(() => {
      window.addEventListener("scroll", updateShareLinksStat);
    });
    return {
      pageRoutes,
      BlogCardData,
      shareLinks,
    };
  },
});

export default Blog3;
</script>

// hexadash-svelte/hexadash/src/lib/view/pages/BlogDetails.svelte
<script>
// @ts-nocheck

	import { onMount } from 'svelte';
	import { Row, Col } from '@sveltestrap/sveltestrap';

	onMount(() => {
		window.addEventListener('scroll', function (e) {
			let blogContainer = document.querySelector('.blog-details'),
				shareGroup = document.querySelector('.blog-share-top');
			if (blogContainer != null && shareGroup != null) {
				window.pageYOffset <= blogContainer.offsetTop
					? shareGroup.classList.remove('show')
					: window.pageYOffset >= blogContainer.offsetTop &&
					  window.pageYOffset <= blogContainer.offsetTop + blogContainer.clientHeight - 700
					? shareGroup.classList.add('show')
					: shareGroup.classList.remove('show');
			}
		});
	});
</script>

<Row class="justify-content-center">
	<Col xxl={8} lg={10}>
		<div class="blog-details-thumbnail">
			<img src="/img/blog-details.png" alt="" />
		</div>
		<article class="blog-details">
			<div class="blog-details-content">
				<h1 class="main-title mb-30">Know More About Time Management System on your Daily Works</h1>
				<ul class="blog-details-meta">
					<li class="blog-author">
						<a href={'#'}>
							<img src="/img/tm4.png" alt="" />
						</a>
						<a href={'#'}>
							<span>Rabbi Islam Rony</span>
						</a>
					</li>
					<li class="author-name">
						<a href={'#'} rel="bookmark">
							<time class="entry-date published updated" datetime="2022-01-25T10:55:00+06:00"
								>January 25, 2022</time
							>
						</a>
					</li>
					<li class="blog-category">
						<a href={'#'} rel="category tag">Development</a>
					</li>
					<li class="blog-read-time">8 mins read</li>
				</ul>
				<div class="blog-body">
					<p class="mb-20">
						”Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter – not
						harder – so that you get more done in less time, even when time is tight and pressures
						are high. Failing to manage your time damages your effectiveness and causes stress.
					</p>

					<p class="mb-50">
						”Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter – not
						harder – so that you get more done enables you to work smarter.
					</p>

					<h1 class="mb-20">What is Time Management?</h1>
					<p class="mb-30">
						”Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter – not
						harder – so that you get more done in less time, even when time is tight and pressures
						are high. Failing to manage your time damages your effectiveness and causes stress.
					</p>
					<div class="blog-block-image mb-30 pb-10">
						<figure>
							<img class="img-fluid" src="/img/blog-details.png" alt="blog_details" />
						</figure>
					</div>
					<h2 class="mb-20">How Can you Use your Time Properly?</h2>
					<p class="mb-30">
						”Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter – not
						harder – so that you get more done in less time, even when time is tight and pressures
						are high
					</p>
					<blockquote class="blog-block-quote">
						<div class="blog-block-quote__wrapper">
							<div class="top-icon">
								<img class="svg" alt="" src={'/img/svg/topSemicolon.svg'} />
							</div>
							<p>
								Investig ationes demons trave runt lectores legere liusry quod was legunt saepius
								claritas Investig tones haretra dui, nec tincidunt ante mauris eu diam. Phasellus
								verra nisl vitae cursus aei uismod supen dise saepius claritas.
							</p>
						</div>
						<cite>Daniel Brownspan,<span>Founder of Company</span></cite>
					</blockquote>
					<h3 class="mb-20">Value of Time Management</h3>
					<p class="mb-25">
						Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter.
					</p>
					<ul class="mb-50">
						<li>
							<strong>Trim transparent pixels on exports:</strong> Usability design is to improve the
							usability of a product, which is an important.
						</li>
						<li>
							<strong>Crash and bug fixes:</strong> Usability design is to improve the usability of a
							product, which is an important part to guide.
						</li>
					</ul>
					<h4 class="mb-20">How Can you Benefit from Time Management System?</h4>
					<p class="mb-25">
						”Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter.
					</p>
					<ul class="mb-50">
						<li>Only be run by an explicit user action</li>
						<li>Show UI in a single plugin-specific dialog</li>
						<li>
							Make a technology change (described in the next section) that avoided the
							privately-disclosed vulnerabilities.
						</li>
					</ul>
					<h5 class="mb-20">Help Users Fill in Forms</h5>
					<p class="mb-25">
						”Time management” is the process of organizing and planning how to divide your time
						between specific activities. Good time management enables you to work smarter.
					</p>
					<ol class="mb-50">
						<li>Only be run by an explicit user action</li>
						<li>Show UI in a single plugin-specific dialog</li>
						<li>
							Make a technology change (described in the next section) that avoided the
							privately-disclosed vulnerabilities.
						</li>
					</ol>
				</div>
				<div class="blog-tags">
					<ul>
						<li><a href={'#'}>Design Process</a></li>
						<li><a href={'#'}>Prototype</a></li>
						<li><a href={'#'}>Design Process</a></li>
						<li><a href={'#'}>Prototype</a></li>
					</ul>
				</div>
				<div class="blog-share">
					<span>Share this article:</span>
					<ul>
						<li>
							<a href={'#'} class="facebook">
								<i class="uil uil-facebook-f" />
								share
							</a>
						</li>
						<li>
							<a href={'#'} class="twitter">
								<i class="uil uil-twitter" />
								tweet
							</a>
						</li>
						<li>
							<a href={'#'} class="pinterest">
								<i class="lab la-pinterest" />
								share
							</a>
						</li>
						<li>
							<a href={'#'} class="linkedin">
								<i class="uil uil-linkedin" />
								share
							</a>
						</li>
						<li>
							<a href={'#'} class="link copy-to-clickboard">
								<i class="uil uil-copy" />
								copy
							</a>
						</li>
					</ul>
				</div>
				<div class="blog-author-box media">
					<div class="auth-img">
						<img class="w-70" src="/img/author-nav.png" alt="" />
					</div>
					<div class="auth-details media-body">
						<span>Written by</span>
						<h2>Rabbi Islam Rony</h2>
						<p>
							Rabbi Islam Rony is a British writer and social media manager specializing in dynamic
							branding, campaign strategy and content engagement.
						</p>
					</div>
				</div>
			</div>
			<div class="blog-share-top">
				<div class="blog-share-fixed">
					<span>share</span>
					<ul>
						<li>
							<a href={'#'} class="facebook">
								<i class="uil uil-facebook-f" />
							</a>
						</li>
						<li>
							<a href={'#'} class="twitter">
								<i class="uil uil-twitter" />
							</a>
						</li>
						<li>
							<a href={'#'} class="pinterest">
								<i class="lab la-pinterest" />
							</a>
						</li>
						<li>
							<a href={'#'} class="linkedin">
								<i class="uil uil-linkedin" />
							</a>
						</li>
						<li>
							<a href={'#'} class="link copy-to-clickboard">
								<i class="uil uil-copy" />
							</a>
						</li>
					</ul>
				</div>
			</div>
		</article>
	</Col>
</Row>
